#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2012 KYOCERA Corporation
#

#
# Makefile for miscellaneous Sensors drivers.
#
obj-$(CONFIG_MACH_MSM8655_KC_F41_KXUD9_HSDT004A) += alps-input.o hscd_i2c.o kxud9.o
obj-$(CONFIG_MACH_MSM8655_KC_F41_GP2AP003A10F) += gp2ap003a10f.o
